# Generated by Django 3.1 on 2020-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design_Site', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
