# Generated by Django 3.1 on 2020-08-21 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Design_Site', '0005_auto_20200820_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
