# Generated by Django 3.1 on 2020-08-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Design_Site', '0006_intro_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='slug',
        ),
    ]
