# Generated by Django 3.1 on 2020-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design_Site', '0007_remove_intro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
