# Generated by Django 3.1 on 2020-08-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design_Site', '0008_auto_20200821_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
